/**
 * @license
 * Copyright 2024 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import {ApiClient} from './_api_client';
import * as common from './_common';
import {BaseModule} from './_common';
import * as t from './_transformers';
import {PagedItem, Pager} from './pagers';
import * as types from './types';

function partToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  if (common.getValueByPath(fromObject, ['videoMetadata']) !== undefined) {
    throw new Error('videoMetadata parameter is not supported in Gemini API.');
  }

  let fromThought = common.getValueByPath(fromObject, ['thought']);
  if (fromThought !== undefined) {
    common.setValueByPath(toObject, ['thought'], fromThought);
  }

  let fromCodeExecutionResult = common.getValueByPath(fromObject, [
    'codeExecutionResult',
  ]);
  if (fromCodeExecutionResult !== undefined) {
    common.setValueByPath(
      toObject,
      ['codeExecutionResult'],
      fromCodeExecutionResult,
    );
  }

  let fromExecutableCode = common.getValueByPath(fromObject, [
    'executableCode',
  ]);
  if (fromExecutableCode !== undefined) {
    common.setValueByPath(toObject, ['executableCode'], fromExecutableCode);
  }

  let fromFileData = common.getValueByPath(fromObject, ['fileData']);
  if (fromFileData !== undefined) {
    common.setValueByPath(toObject, ['fileData'], fromFileData);
  }

  let fromFunctionCall = common.getValueByPath(fromObject, ['functionCall']);
  if (fromFunctionCall !== undefined) {
    common.setValueByPath(toObject, ['functionCall'], fromFunctionCall);
  }

  let fromFunctionResponse = common.getValueByPath(fromObject, [
    'functionResponse',
  ]);
  if (fromFunctionResponse !== undefined) {
    common.setValueByPath(toObject, ['functionResponse'], fromFunctionResponse);
  }

  let fromInlineData = common.getValueByPath(fromObject, ['inlineData']);
  if (fromInlineData !== undefined) {
    common.setValueByPath(toObject, ['inlineData'], fromInlineData);
  }

  let fromText = common.getValueByPath(fromObject, ['text']);
  if (fromText !== undefined) {
    common.setValueByPath(toObject, ['text'], fromText);
  }

  return toObject;
}

function partToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromVideoMetadata = common.getValueByPath(fromObject, ['videoMetadata']);
  if (fromVideoMetadata !== undefined) {
    common.setValueByPath(toObject, ['videoMetadata'], fromVideoMetadata);
  }

  let fromThought = common.getValueByPath(fromObject, ['thought']);
  if (fromThought !== undefined) {
    common.setValueByPath(toObject, ['thought'], fromThought);
  }

  let fromCodeExecutionResult = common.getValueByPath(fromObject, [
    'codeExecutionResult',
  ]);
  if (fromCodeExecutionResult !== undefined) {
    common.setValueByPath(
      toObject,
      ['codeExecutionResult'],
      fromCodeExecutionResult,
    );
  }

  let fromExecutableCode = common.getValueByPath(fromObject, [
    'executableCode',
  ]);
  if (fromExecutableCode !== undefined) {
    common.setValueByPath(toObject, ['executableCode'], fromExecutableCode);
  }

  let fromFileData = common.getValueByPath(fromObject, ['fileData']);
  if (fromFileData !== undefined) {
    common.setValueByPath(toObject, ['fileData'], fromFileData);
  }

  let fromFunctionCall = common.getValueByPath(fromObject, ['functionCall']);
  if (fromFunctionCall !== undefined) {
    common.setValueByPath(toObject, ['functionCall'], fromFunctionCall);
  }

  let fromFunctionResponse = common.getValueByPath(fromObject, [
    'functionResponse',
  ]);
  if (fromFunctionResponse !== undefined) {
    common.setValueByPath(toObject, ['functionResponse'], fromFunctionResponse);
  }

  let fromInlineData = common.getValueByPath(fromObject, ['inlineData']);
  if (fromInlineData !== undefined) {
    common.setValueByPath(toObject, ['inlineData'], fromInlineData);
  }

  let fromText = common.getValueByPath(fromObject, ['text']);
  if (fromText !== undefined) {
    common.setValueByPath(toObject, ['text'], fromText);
  }

  return toObject;
}

export function contentToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromParts = common.getValueByPath(fromObject, ['parts']);
  if (fromParts !== undefined) {
    common.setValueByPath(
      toObject,
      ['parts'],
      fromParts!.map((item: any) => {
        return partToMldev(apiClient, item, toObject);
      }),
    );
  }

  let fromRole = common.getValueByPath(fromObject, ['role']);
  if (fromRole !== undefined) {
    common.setValueByPath(toObject, ['role'], fromRole);
  }

  return toObject;
}

export function contentToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromParts = common.getValueByPath(fromObject, ['parts']);
  if (fromParts !== undefined) {
    common.setValueByPath(
      toObject,
      ['parts'],
      fromParts!.map((item: any) => {
        return partToVertex(apiClient, item, toObject);
      }),
    );
  }

  let fromRole = common.getValueByPath(fromObject, ['role']);
  if (fromRole !== undefined) {
    common.setValueByPath(toObject, ['role'], fromRole);
  }

  return toObject;
}

function schemaToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  if (common.getValueByPath(fromObject, ['minItems']) !== undefined) {
    throw new Error('minItems parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['example']) !== undefined) {
    throw new Error('example parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['propertyOrdering']) !== undefined) {
    throw new Error(
      'propertyOrdering parameter is not supported in Gemini API.',
    );
  }

  if (common.getValueByPath(fromObject, ['pattern']) !== undefined) {
    throw new Error('pattern parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['minimum']) !== undefined) {
    throw new Error('minimum parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['default']) !== undefined) {
    throw new Error('default parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['anyOf']) !== undefined) {
    throw new Error('anyOf parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['maxLength']) !== undefined) {
    throw new Error('maxLength parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['title']) !== undefined) {
    throw new Error('title parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['minLength']) !== undefined) {
    throw new Error('minLength parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['minProperties']) !== undefined) {
    throw new Error('minProperties parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['maxItems']) !== undefined) {
    throw new Error('maxItems parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['maximum']) !== undefined) {
    throw new Error('maximum parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['nullable']) !== undefined) {
    throw new Error('nullable parameter is not supported in Gemini API.');
  }

  if (common.getValueByPath(fromObject, ['maxProperties']) !== undefined) {
    throw new Error('maxProperties parameter is not supported in Gemini API.');
  }

  let fromType = common.getValueByPath(fromObject, ['type']);
  if (fromType !== undefined) {
    common.setValueByPath(toObject, ['type'], fromType);
  }

  let fromDescription = common.getValueByPath(fromObject, ['description']);
  if (fromDescription !== undefined) {
    common.setValueByPath(toObject, ['description'], fromDescription);
  }

  let fromEnum = common.getValueByPath(fromObject, ['enum']);
  if (fromEnum !== undefined) {
    common.setValueByPath(toObject, ['enum'], fromEnum);
  }

  let fromFormat = common.getValueByPath(fromObject, ['format']);
  if (fromFormat !== undefined) {
    common.setValueByPath(toObject, ['format'], fromFormat);
  }

  let fromItems = common.getValueByPath(fromObject, ['items']);
  if (fromItems !== undefined) {
    common.setValueByPath(toObject, ['items'], fromItems);
  }

  let fromProperties = common.getValueByPath(fromObject, ['properties']);
  if (fromProperties !== undefined) {
    common.setValueByPath(toObject, ['properties'], fromProperties);
  }

  let fromRequired = common.getValueByPath(fromObject, ['required']);
  if (fromRequired !== undefined) {
    common.setValueByPath(toObject, ['required'], fromRequired);
  }

  return toObject;
}

function schemaToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromMinItems = common.getValueByPath(fromObject, ['minItems']);
  if (fromMinItems !== undefined) {
    common.setValueByPath(toObject, ['minItems'], fromMinItems);
  }

  let fromExample = common.getValueByPath(fromObject, ['example']);
  if (fromExample !== undefined) {
    common.setValueByPath(toObject, ['example'], fromExample);
  }

  let fromPropertyOrdering = common.getValueByPath(fromObject, [
    'propertyOrdering',
  ]);
  if (fromPropertyOrdering !== undefined) {
    common.setValueByPath(toObject, ['propertyOrdering'], fromPropertyOrdering);
  }

  let fromPattern = common.getValueByPath(fromObject, ['pattern']);
  if (fromPattern !== undefined) {
    common.setValueByPath(toObject, ['pattern'], fromPattern);
  }

  let fromMinimum = common.getValueByPath(fromObject, ['minimum']);
  if (fromMinimum !== undefined) {
    common.setValueByPath(toObject, ['minimum'], fromMinimum);
  }

  let fromDefault = common.getValueByPath(fromObject, ['default']);
  if (fromDefault !== undefined) {
    common.setValueByPath(toObject, ['default'], fromDefault);
  }

  let fromAnyOf = common.getValueByPath(fromObject, ['anyOf']);
  if (fromAnyOf !== undefined) {
    common.setValueByPath(toObject, ['anyOf'], fromAnyOf);
  }

  let fromMaxLength = common.getValueByPath(fromObject, ['maxLength']);
  if (fromMaxLength !== undefined) {
    common.setValueByPath(toObject, ['maxLength'], fromMaxLength);
  }

  let fromTitle = common.getValueByPath(fromObject, ['title']);
  if (fromTitle !== undefined) {
    common.setValueByPath(toObject, ['title'], fromTitle);
  }

  let fromMinLength = common.getValueByPath(fromObject, ['minLength']);
  if (fromMinLength !== undefined) {
    common.setValueByPath(toObject, ['minLength'], fromMinLength);
  }

  let fromMinProperties = common.getValueByPath(fromObject, ['minProperties']);
  if (fromMinProperties !== undefined) {
    common.setValueByPath(toObject, ['minProperties'], fromMinProperties);
  }

  let fromMaxItems = common.getValueByPath(fromObject, ['maxItems']);
  if (fromMaxItems !== undefined) {
    common.setValueByPath(toObject, ['maxItems'], fromMaxItems);
  }

  let fromMaximum = common.getValueByPath(fromObject, ['maximum']);
  if (fromMaximum !== undefined) {
    common.setValueByPath(toObject, ['maximum'], fromMaximum);
  }

  let fromNullable = common.getValueByPath(fromObject, ['nullable']);
  if (fromNullable !== undefined) {
    common.setValueByPath(toObject, ['nullable'], fromNullable);
  }

  let fromMaxProperties = common.getValueByPath(fromObject, ['maxProperties']);
  if (fromMaxProperties !== undefined) {
    common.setValueByPath(toObject, ['maxProperties'], fromMaxProperties);
  }

  let fromType = common.getValueByPath(fromObject, ['type']);
  if (fromType !== undefined) {
    common.setValueByPath(toObject, ['type'], fromType);
  }

  let fromDescription = common.getValueByPath(fromObject, ['description']);
  if (fromDescription !== undefined) {
    common.setValueByPath(toObject, ['description'], fromDescription);
  }

  let fromEnum = common.getValueByPath(fromObject, ['enum']);
  if (fromEnum !== undefined) {
    common.setValueByPath(toObject, ['enum'], fromEnum);
  }

  let fromFormat = common.getValueByPath(fromObject, ['format']);
  if (fromFormat !== undefined) {
    common.setValueByPath(toObject, ['format'], fromFormat);
  }

  let fromItems = common.getValueByPath(fromObject, ['items']);
  if (fromItems !== undefined) {
    common.setValueByPath(toObject, ['items'], fromItems);
  }

  let fromProperties = common.getValueByPath(fromObject, ['properties']);
  if (fromProperties !== undefined) {
    common.setValueByPath(toObject, ['properties'], fromProperties);
  }

  let fromRequired = common.getValueByPath(fromObject, ['required']);
  if (fromRequired !== undefined) {
    common.setValueByPath(toObject, ['required'], fromRequired);
  }

  return toObject;
}

function functionDeclarationToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  if (common.getValueByPath(fromObject, ['response']) !== undefined) {
    throw new Error('response parameter is not supported in Gemini API.');
  }

  let fromDescription = common.getValueByPath(fromObject, ['description']);
  if (fromDescription !== undefined) {
    common.setValueByPath(toObject, ['description'], fromDescription);
  }

  let fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName !== undefined) {
    common.setValueByPath(toObject, ['name'], fromName);
  }

  let fromParameters = common.getValueByPath(fromObject, ['parameters']);
  if (fromParameters !== undefined) {
    common.setValueByPath(toObject, ['parameters'], fromParameters);
  }

  return toObject;
}

function functionDeclarationToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromResponse = common.getValueByPath(fromObject, ['response']);
  if (fromResponse !== undefined) {
    common.setValueByPath(
      toObject,
      ['response'],
      schemaToVertex(apiClient, fromResponse, toObject),
    );
  }

  let fromDescription = common.getValueByPath(fromObject, ['description']);
  if (fromDescription !== undefined) {
    common.setValueByPath(toObject, ['description'], fromDescription);
  }

  let fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName !== undefined) {
    common.setValueByPath(toObject, ['name'], fromName);
  }

  let fromParameters = common.getValueByPath(fromObject, ['parameters']);
  if (fromParameters !== undefined) {
    common.setValueByPath(toObject, ['parameters'], fromParameters);
  }

  return toObject;
}

function googleSearchToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  return toObject;
}

function googleSearchToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  return toObject;
}

function dynamicRetrievalConfigToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromMode = common.getValueByPath(fromObject, ['mode']);
  if (fromMode !== undefined) {
    common.setValueByPath(toObject, ['mode'], fromMode);
  }

  let fromDynamicThreshold = common.getValueByPath(fromObject, [
    'dynamicThreshold',
  ]);
  if (fromDynamicThreshold !== undefined) {
    common.setValueByPath(toObject, ['dynamicThreshold'], fromDynamicThreshold);
  }

  return toObject;
}

function dynamicRetrievalConfigToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromMode = common.getValueByPath(fromObject, ['mode']);
  if (fromMode !== undefined) {
    common.setValueByPath(toObject, ['mode'], fromMode);
  }

  let fromDynamicThreshold = common.getValueByPath(fromObject, [
    'dynamicThreshold',
  ]);
  if (fromDynamicThreshold !== undefined) {
    common.setValueByPath(toObject, ['dynamicThreshold'], fromDynamicThreshold);
  }

  return toObject;
}

function googleSearchRetrievalToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromDynamicRetrievalConfig = common.getValueByPath(fromObject, [
    'dynamicRetrievalConfig',
  ]);
  if (fromDynamicRetrievalConfig !== undefined) {
    common.setValueByPath(
      toObject,
      ['dynamicRetrievalConfig'],
      dynamicRetrievalConfigToMldev(
        apiClient,
        fromDynamicRetrievalConfig,
        toObject,
      ),
    );
  }

  return toObject;
}

function googleSearchRetrievalToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromDynamicRetrievalConfig = common.getValueByPath(fromObject, [
    'dynamicRetrievalConfig',
  ]);
  if (fromDynamicRetrievalConfig !== undefined) {
    common.setValueByPath(
      toObject,
      ['dynamicRetrievalConfig'],
      dynamicRetrievalConfigToVertex(
        apiClient,
        fromDynamicRetrievalConfig,
        toObject,
      ),
    );
  }

  return toObject;
}

export function toolToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromFunctionDeclarations = common.getValueByPath(fromObject, [
    'functionDeclarations',
  ]);
  if (fromFunctionDeclarations !== undefined) {
    common.setValueByPath(
      toObject,
      ['functionDeclarations'],
      fromFunctionDeclarations!.map((item: any) => {
        return functionDeclarationToMldev(apiClient, item, toObject);
      }),
    );
  }

  if (common.getValueByPath(fromObject, ['retrieval']) !== undefined) {
    throw new Error('retrieval parameter is not supported in Gemini API.');
  }

  let fromGoogleSearch = common.getValueByPath(fromObject, ['googleSearch']);
  if (fromGoogleSearch !== undefined) {
    common.setValueByPath(
      toObject,
      ['googleSearch'],
      googleSearchToMldev(apiClient, fromGoogleSearch, toObject),
    );
  }

  let fromGoogleSearchRetrieval = common.getValueByPath(fromObject, [
    'googleSearchRetrieval',
  ]);
  if (fromGoogleSearchRetrieval !== undefined) {
    common.setValueByPath(
      toObject,
      ['googleSearchRetrieval'],
      googleSearchRetrievalToMldev(
        apiClient,
        fromGoogleSearchRetrieval,
        toObject,
      ),
    );
  }

  let fromCodeExecution = common.getValueByPath(fromObject, ['codeExecution']);
  if (fromCodeExecution !== undefined) {
    common.setValueByPath(toObject, ['codeExecution'], fromCodeExecution);
  }

  return toObject;
}

export function toolToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromFunctionDeclarations = common.getValueByPath(fromObject, [
    'functionDeclarations',
  ]);
  if (fromFunctionDeclarations !== undefined) {
    common.setValueByPath(
      toObject,
      ['functionDeclarations'],
      fromFunctionDeclarations!.map((item: any) => {
        return functionDeclarationToVertex(apiClient, item, toObject);
      }),
    );
  }

  let fromRetrieval = common.getValueByPath(fromObject, ['retrieval']);
  if (fromRetrieval !== undefined) {
    common.setValueByPath(toObject, ['retrieval'], fromRetrieval);
  }

  let fromGoogleSearch = common.getValueByPath(fromObject, ['googleSearch']);
  if (fromGoogleSearch !== undefined) {
    common.setValueByPath(
      toObject,
      ['googleSearch'],
      googleSearchToVertex(apiClient, fromGoogleSearch, toObject),
    );
  }

  let fromGoogleSearchRetrieval = common.getValueByPath(fromObject, [
    'googleSearchRetrieval',
  ]);
  if (fromGoogleSearchRetrieval !== undefined) {
    common.setValueByPath(
      toObject,
      ['googleSearchRetrieval'],
      googleSearchRetrievalToVertex(
        apiClient,
        fromGoogleSearchRetrieval,
        toObject,
      ),
    );
  }

  let fromCodeExecution = common.getValueByPath(fromObject, ['codeExecution']);
  if (fromCodeExecution !== undefined) {
    common.setValueByPath(toObject, ['codeExecution'], fromCodeExecution);
  }

  return toObject;
}

function functionCallingConfigToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromMode = common.getValueByPath(fromObject, ['mode']);
  if (fromMode !== undefined) {
    common.setValueByPath(toObject, ['mode'], fromMode);
  }

  let fromAllowedFunctionNames = common.getValueByPath(fromObject, [
    'allowedFunctionNames',
  ]);
  if (fromAllowedFunctionNames !== undefined) {
    common.setValueByPath(
      toObject,
      ['allowedFunctionNames'],
      fromAllowedFunctionNames,
    );
  }

  return toObject;
}

function functionCallingConfigToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromMode = common.getValueByPath(fromObject, ['mode']);
  if (fromMode !== undefined) {
    common.setValueByPath(toObject, ['mode'], fromMode);
  }

  let fromAllowedFunctionNames = common.getValueByPath(fromObject, [
    'allowedFunctionNames',
  ]);
  if (fromAllowedFunctionNames !== undefined) {
    common.setValueByPath(
      toObject,
      ['allowedFunctionNames'],
      fromAllowedFunctionNames,
    );
  }

  return toObject;
}

function toolConfigToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromFunctionCallingConfig = common.getValueByPath(fromObject, [
    'functionCallingConfig',
  ]);
  if (fromFunctionCallingConfig !== undefined) {
    common.setValueByPath(
      toObject,
      ['functionCallingConfig'],
      functionCallingConfigToMldev(
        apiClient,
        fromFunctionCallingConfig,
        toObject,
      ),
    );
  }

  return toObject;
}

function toolConfigToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromFunctionCallingConfig = common.getValueByPath(fromObject, [
    'functionCallingConfig',
  ]);
  if (fromFunctionCallingConfig !== undefined) {
    common.setValueByPath(
      toObject,
      ['functionCallingConfig'],
      functionCallingConfigToVertex(
        apiClient,
        fromFunctionCallingConfig,
        toObject,
      ),
    );
  }

  return toObject;
}

function createCachedContentConfigToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromTtl = common.getValueByPath(fromObject, ['ttl']);
  if (fromTtl !== undefined) {
    common.setValueByPath(parentObject, ['ttl'], fromTtl);
  }

  let fromExpireTime = common.getValueByPath(fromObject, ['expireTime']);
  if (fromExpireTime !== undefined) {
    common.setValueByPath(parentObject, ['expireTime'], fromExpireTime);
  }

  let fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (fromDisplayName !== undefined) {
    common.setValueByPath(parentObject, ['displayName'], fromDisplayName);
  }

  let fromContents = common.getValueByPath(fromObject, ['contents']);
  if (fromContents !== undefined) {
    common.setValueByPath(
      parentObject,
      ['contents'],
      t.tContents(
        apiClient,
        t.tContents(apiClient, fromContents)!.map((item: any) => {
          return contentToMldev(apiClient, item, toObject);
        }),
      ),
    );
  }

  let fromSystemInstruction = common.getValueByPath(fromObject, [
    'systemInstruction',
  ]);
  if (fromSystemInstruction !== undefined) {
    common.setValueByPath(
      parentObject,
      ['systemInstruction'],
      contentToMldev(
        apiClient,
        t.tContent(apiClient, fromSystemInstruction),
        toObject,
      ),
    );
  }

  let fromTools = common.getValueByPath(fromObject, ['tools']);
  if (fromTools !== undefined) {
    common.setValueByPath(
      parentObject,
      ['tools'],
      fromTools!.map((item: any) => {
        return toolToMldev(apiClient, item, toObject);
      }),
    );
  }

  let fromToolConfig = common.getValueByPath(fromObject, ['toolConfig']);
  if (fromToolConfig !== undefined) {
    common.setValueByPath(
      parentObject,
      ['toolConfig'],
      toolConfigToMldev(apiClient, fromToolConfig, toObject),
    );
  }

  return toObject;
}

function createCachedContentConfigToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromTtl = common.getValueByPath(fromObject, ['ttl']);
  if (fromTtl !== undefined) {
    common.setValueByPath(parentObject, ['ttl'], fromTtl);
  }

  let fromExpireTime = common.getValueByPath(fromObject, ['expireTime']);
  if (fromExpireTime !== undefined) {
    common.setValueByPath(parentObject, ['expireTime'], fromExpireTime);
  }

  let fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (fromDisplayName !== undefined) {
    common.setValueByPath(parentObject, ['displayName'], fromDisplayName);
  }

  let fromContents = common.getValueByPath(fromObject, ['contents']);
  if (fromContents !== undefined) {
    common.setValueByPath(
      parentObject,
      ['contents'],
      t.tContents(
        apiClient,
        t.tContents(apiClient, fromContents)!.map((item: any) => {
          return contentToVertex(apiClient, item, toObject);
        }),
      ),
    );
  }

  let fromSystemInstruction = common.getValueByPath(fromObject, [
    'systemInstruction',
  ]);
  if (fromSystemInstruction !== undefined) {
    common.setValueByPath(
      parentObject,
      ['systemInstruction'],
      contentToVertex(
        apiClient,
        t.tContent(apiClient, fromSystemInstruction),
        toObject,
      ),
    );
  }

  let fromTools = common.getValueByPath(fromObject, ['tools']);
  if (fromTools !== undefined) {
    common.setValueByPath(
      parentObject,
      ['tools'],
      fromTools!.map((item: any) => {
        return toolToVertex(apiClient, item, toObject);
      }),
    );
  }

  let fromToolConfig = common.getValueByPath(fromObject, ['toolConfig']);
  if (fromToolConfig !== undefined) {
    common.setValueByPath(
      parentObject,
      ['toolConfig'],
      toolConfigToVertex(apiClient, fromToolConfig, toObject),
    );
  }

  return toObject;
}

function createCachedContentParametersToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromModel = common.getValueByPath(fromObject, ['model']);
  if (fromModel !== undefined) {
    common.setValueByPath(
      toObject,
      ['model'],
      t.tCachesModel(apiClient, fromModel),
    );
  }

  let fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig !== undefined) {
    common.setValueByPath(
      toObject,
      ['config'],
      createCachedContentConfigToMldev(apiClient, fromConfig, toObject),
    );
  }

  return toObject;
}

function createCachedContentParametersToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromModel = common.getValueByPath(fromObject, ['model']);
  if (fromModel !== undefined) {
    common.setValueByPath(
      toObject,
      ['model'],
      t.tCachesModel(apiClient, fromModel),
    );
  }

  let fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig !== undefined) {
    common.setValueByPath(
      toObject,
      ['config'],
      createCachedContentConfigToVertex(apiClient, fromConfig, toObject),
    );
  }

  return toObject;
}

function getCachedContentParametersToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName !== undefined) {
    common.setValueByPath(
      toObject,
      ['_url', 'name'],
      t.tCachedContentName(apiClient, fromName),
    );
  }

  let fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig !== undefined) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

function getCachedContentParametersToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName !== undefined) {
    common.setValueByPath(
      toObject,
      ['_url', 'name'],
      t.tCachedContentName(apiClient, fromName),
    );
  }

  let fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig !== undefined) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

function deleteCachedContentParametersToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName !== undefined) {
    common.setValueByPath(
      toObject,
      ['_url', 'name'],
      t.tCachedContentName(apiClient, fromName),
    );
  }

  let fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig !== undefined) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

function deleteCachedContentParametersToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName !== undefined) {
    common.setValueByPath(
      toObject,
      ['_url', 'name'],
      t.tCachedContentName(apiClient, fromName),
    );
  }

  let fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig !== undefined) {
    common.setValueByPath(toObject, ['config'], fromConfig);
  }

  return toObject;
}

function updateCachedContentConfigToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromTtl = common.getValueByPath(fromObject, ['ttl']);
  if (fromTtl !== undefined) {
    common.setValueByPath(parentObject, ['ttl'], fromTtl);
  }

  let fromExpireTime = common.getValueByPath(fromObject, ['expireTime']);
  if (fromExpireTime !== undefined) {
    common.setValueByPath(parentObject, ['expireTime'], fromExpireTime);
  }

  return toObject;
}

function updateCachedContentConfigToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromTtl = common.getValueByPath(fromObject, ['ttl']);
  if (fromTtl !== undefined) {
    common.setValueByPath(parentObject, ['ttl'], fromTtl);
  }

  let fromExpireTime = common.getValueByPath(fromObject, ['expireTime']);
  if (fromExpireTime !== undefined) {
    common.setValueByPath(parentObject, ['expireTime'], fromExpireTime);
  }

  return toObject;
}

function updateCachedContentParametersToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName !== undefined) {
    common.setValueByPath(
      toObject,
      ['_url', 'name'],
      t.tCachedContentName(apiClient, fromName),
    );
  }

  let fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig !== undefined) {
    common.setValueByPath(
      toObject,
      ['config'],
      updateCachedContentConfigToMldev(apiClient, fromConfig, toObject),
    );
  }

  return toObject;
}

function updateCachedContentParametersToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName !== undefined) {
    common.setValueByPath(
      toObject,
      ['_url', 'name'],
      t.tCachedContentName(apiClient, fromName),
    );
  }

  let fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig !== undefined) {
    common.setValueByPath(
      toObject,
      ['config'],
      updateCachedContentConfigToVertex(apiClient, fromConfig, toObject),
    );
  }

  return toObject;
}

function listCachedContentsConfigToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromPageSize = common.getValueByPath(fromObject, ['pageSize']);
  if (fromPageSize !== undefined) {
    common.setValueByPath(parentObject, ['_query', 'pageSize'], fromPageSize);
  }

  let fromPageToken = common.getValueByPath(fromObject, ['pageToken']);
  if (fromPageToken !== undefined) {
    common.setValueByPath(parentObject, ['_query', 'pageToken'], fromPageToken);
  }

  return toObject;
}

function listCachedContentsConfigToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromPageSize = common.getValueByPath(fromObject, ['pageSize']);
  if (fromPageSize !== undefined) {
    common.setValueByPath(parentObject, ['_query', 'pageSize'], fromPageSize);
  }

  let fromPageToken = common.getValueByPath(fromObject, ['pageToken']);
  if (fromPageToken !== undefined) {
    common.setValueByPath(parentObject, ['_query', 'pageToken'], fromPageToken);
  }

  return toObject;
}

function listCachedContentsParametersToMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig !== undefined) {
    common.setValueByPath(
      toObject,
      ['config'],
      listCachedContentsConfigToMldev(apiClient, fromConfig, toObject),
    );
  }

  return toObject;
}

function listCachedContentsParametersToVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromConfig = common.getValueByPath(fromObject, ['config']);
  if (fromConfig !== undefined) {
    common.setValueByPath(
      toObject,
      ['config'],
      listCachedContentsConfigToVertex(apiClient, fromConfig, toObject),
    );
  }

  return toObject;
}

function cachedContentFromMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName !== undefined) {
    common.setValueByPath(toObject, ['name'], fromName);
  }

  let fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (fromDisplayName !== undefined) {
    common.setValueByPath(toObject, ['displayName'], fromDisplayName);
  }

  let fromModel = common.getValueByPath(fromObject, ['model']);
  if (fromModel !== undefined) {
    common.setValueByPath(toObject, ['model'], fromModel);
  }

  let fromCreateTime = common.getValueByPath(fromObject, ['createTime']);
  if (fromCreateTime !== undefined) {
    common.setValueByPath(toObject, ['createTime'], fromCreateTime);
  }

  let fromUpdateTime = common.getValueByPath(fromObject, ['updateTime']);
  if (fromUpdateTime !== undefined) {
    common.setValueByPath(toObject, ['updateTime'], fromUpdateTime);
  }

  let fromExpireTime = common.getValueByPath(fromObject, ['expireTime']);
  if (fromExpireTime !== undefined) {
    common.setValueByPath(toObject, ['expireTime'], fromExpireTime);
  }

  let fromUsageMetadata = common.getValueByPath(fromObject, ['usageMetadata']);
  if (fromUsageMetadata !== undefined) {
    common.setValueByPath(toObject, ['usageMetadata'], fromUsageMetadata);
  }

  return toObject;
}

function cachedContentFromVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromName = common.getValueByPath(fromObject, ['name']);
  if (fromName !== undefined) {
    common.setValueByPath(toObject, ['name'], fromName);
  }

  let fromDisplayName = common.getValueByPath(fromObject, ['displayName']);
  if (fromDisplayName !== undefined) {
    common.setValueByPath(toObject, ['displayName'], fromDisplayName);
  }

  let fromModel = common.getValueByPath(fromObject, ['model']);
  if (fromModel !== undefined) {
    common.setValueByPath(toObject, ['model'], fromModel);
  }

  let fromCreateTime = common.getValueByPath(fromObject, ['createTime']);
  if (fromCreateTime !== undefined) {
    common.setValueByPath(toObject, ['createTime'], fromCreateTime);
  }

  let fromUpdateTime = common.getValueByPath(fromObject, ['updateTime']);
  if (fromUpdateTime !== undefined) {
    common.setValueByPath(toObject, ['updateTime'], fromUpdateTime);
  }

  let fromExpireTime = common.getValueByPath(fromObject, ['expireTime']);
  if (fromExpireTime !== undefined) {
    common.setValueByPath(toObject, ['expireTime'], fromExpireTime);
  }

  let fromUsageMetadata = common.getValueByPath(fromObject, ['usageMetadata']);
  if (fromUsageMetadata !== undefined) {
    common.setValueByPath(toObject, ['usageMetadata'], fromUsageMetadata);
  }

  return toObject;
}

function deleteCachedContentResponseFromMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  return toObject;
}

function deleteCachedContentResponseFromVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  return toObject;
}

function listCachedContentsResponseFromMldev(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromNextPageToken = common.getValueByPath(fromObject, ['nextPageToken']);
  if (fromNextPageToken !== undefined) {
    common.setValueByPath(toObject, ['nextPageToken'], fromNextPageToken);
  }

  let fromCachedContents = common.getValueByPath(fromObject, [
    'cachedContents',
  ]);
  if (fromCachedContents !== undefined) {
    common.setValueByPath(
      toObject,
      ['cachedContents'],
      fromCachedContents!.map((item: any) => {
        return cachedContentFromMldev(apiClient, item, toObject);
      }),
    );
  }

  return toObject;
}

function listCachedContentsResponseFromVertex(
  apiClient: ApiClient,
  fromObject: any,
  parentObject?: any,
): Record<string, any> {
  let toObject: Record<string, any> = {};

  let fromNextPageToken = common.getValueByPath(fromObject, ['nextPageToken']);
  if (fromNextPageToken !== undefined) {
    common.setValueByPath(toObject, ['nextPageToken'], fromNextPageToken);
  }

  let fromCachedContents = common.getValueByPath(fromObject, [
    'cachedContents',
  ]);
  if (fromCachedContents !== undefined) {
    common.setValueByPath(
      toObject,
      ['cachedContents'],
      fromCachedContents!.map((item: any) => {
        return cachedContentFromVertex(apiClient, item, toObject);
      }),
    );
  }

  return toObject;
}

export class Caches extends BaseModule {
  constructor(private readonly apiClient: ApiClient) {
    super();
  }

  async create(
    model: string,
    config?: types.CreateCachedContentConfig,
  ): Promise<types.CachedContent> {
    let response: Promise<types.CachedContent>;
    let path: string = '';
    let body: Record<string, any> = {};
    let kwargs: Record<string, any> = {};
    kwargs['model'] = model;
    kwargs['config'] = config;
    if (this.apiClient.isVertexAI()) {
      body = createCachedContentParametersToVertex(this.apiClient, kwargs);
      path = common.formatMap('cachedContents', body['_url']);
      delete body['config']; // TODO: Remove this hack for removing config.
      response = this.apiClient.post(path, body, undefined);

      return response.then((apiResponse) => {
        const resp = cachedContentFromVertex(this.apiClient, apiResponse);

        return resp as types.CachedContent;
      });
    } else {
      body = createCachedContentParametersToMldev(this.apiClient, kwargs);
      path = common.formatMap('cachedContents', body['_url']);
      delete body['config']; // TODO: Remove this hack for removing config.
      response = this.apiClient.post(path, body, undefined);

      return response.then((apiResponse) => {
        const resp = cachedContentFromMldev(this.apiClient, apiResponse);

        return resp as types.CachedContent;
      });
    }
  }

  async get(
    name: string,
    config?: types.GetCachedContentConfig,
  ): Promise<types.CachedContent> {
    let response: Promise<types.CachedContent>;
    let path: string = '';
    let body: Record<string, any> = {};
    let kwargs: Record<string, any> = {};
    kwargs['name'] = name;
    kwargs['config'] = config;
    if (this.apiClient.isVertexAI()) {
      body = getCachedContentParametersToVertex(this.apiClient, kwargs);
      path = common.formatMap('{name}', body['_url']);
      delete body['config']; // TODO: Remove this hack for removing config.
      response = this.apiClient.get(path, body, undefined);

      return response.then((apiResponse) => {
        const resp = cachedContentFromVertex(this.apiClient, apiResponse);

        return resp as types.CachedContent;
      });
    } else {
      body = getCachedContentParametersToMldev(this.apiClient, kwargs);
      path = common.formatMap('{name}', body['_url']);
      delete body['config']; // TODO: Remove this hack for removing config.
      response = this.apiClient.get(path, body, undefined);

      return response.then((apiResponse) => {
        const resp = cachedContentFromMldev(this.apiClient, apiResponse);

        return resp as types.CachedContent;
      });
    }
  }

  async delete(
    name: string,
    config?: types.DeleteCachedContentConfig,
  ): Promise<types.DeleteCachedContentResponse> {
    let response: Promise<types.DeleteCachedContentResponse>;
    let path: string = '';
    let body: Record<string, any> = {};
    let kwargs: Record<string, any> = {};
    kwargs['name'] = name;
    kwargs['config'] = config;
    if (this.apiClient.isVertexAI()) {
      body = deleteCachedContentParametersToVertex(this.apiClient, kwargs);
      path = common.formatMap('{name}', body['_url']);
      delete body['config']; // TODO: Remove this hack for removing config.
      response = this.apiClient.delete(
        path,
        body,
        types.DeleteCachedContentResponse,
      );

      return response.then((apiResponse) => {
        const resp = deleteCachedContentResponseFromVertex(
          this.apiClient,
          apiResponse,
        );
        Object.setPrototypeOf(
          resp,
          types.DeleteCachedContentResponse.prototype,
        );
        return resp as types.DeleteCachedContentResponse;
      });
    } else {
      body = deleteCachedContentParametersToMldev(this.apiClient, kwargs);
      path = common.formatMap('{name}', body['_url']);
      delete body['config']; // TODO: Remove this hack for removing config.
      response = this.apiClient.delete(
        path,
        body,
        types.DeleteCachedContentResponse,
      );

      return response.then((apiResponse) => {
        const resp = deleteCachedContentResponseFromMldev(
          this.apiClient,
          apiResponse,
        );
        Object.setPrototypeOf(
          resp,
          types.DeleteCachedContentResponse.prototype,
        );
        return resp as types.DeleteCachedContentResponse;
      });
    }
  }

  async update(
    name: string,
    config?: types.UpdateCachedContentConfig,
  ): Promise<types.CachedContent> {
    let response: Promise<types.CachedContent>;
    let path: string = '';
    let body: Record<string, any> = {};
    let kwargs: Record<string, any> = {};
    kwargs['name'] = name;
    kwargs['config'] = config;
    if (this.apiClient.isVertexAI()) {
      body = updateCachedContentParametersToVertex(this.apiClient, kwargs);
      path = common.formatMap('{name}', body['_url']);
      delete body['config']; // TODO: Remove this hack for removing config.
      response = this.apiClient.patch(path, body, undefined);

      return response.then((apiResponse) => {
        const resp = cachedContentFromVertex(this.apiClient, apiResponse);

        return resp as types.CachedContent;
      });
    } else {
      body = updateCachedContentParametersToMldev(this.apiClient, kwargs);
      path = common.formatMap('{name}', body['_url']);
      delete body['config']; // TODO: Remove this hack for removing config.
      response = this.apiClient.patch(path, body, undefined);

      return response.then((apiResponse) => {
        const resp = cachedContentFromMldev(this.apiClient, apiResponse);

        return resp as types.CachedContent;
      });
    }
  }

  private async _list(
    config?: types.ListCachedContentsConfig,
  ): Promise<types.ListCachedContentsResponse> {
    let response: Promise<types.ListCachedContentsResponse>;
    let path: string = '';
    let body: Record<string, any> = {};
    let kwargs: Record<string, any> = {};
    kwargs['config'] = config;
    if (this.apiClient.isVertexAI()) {
      body = listCachedContentsParametersToVertex(this.apiClient, kwargs);
      path = common.formatMap('cachedContents', body['_url']);
      delete body['config']; // TODO: Remove this hack for removing config.
      response = this.apiClient.get(
        path,
        body,
        types.ListCachedContentsResponse,
      );

      return response.then((apiResponse) => {
        const resp = listCachedContentsResponseFromVertex(
          this.apiClient,
          apiResponse,
        );
        Object.setPrototypeOf(resp, types.ListCachedContentsResponse.prototype);
        return resp as types.ListCachedContentsResponse;
      });
    } else {
      body = listCachedContentsParametersToMldev(this.apiClient, kwargs);
      path = common.formatMap('cachedContents', body['_url']);
      delete body['config']; // TODO: Remove this hack for removing config.
      response = this.apiClient.get(
        path,
        body,
        types.ListCachedContentsResponse,
      );

      return response.then((apiResponse) => {
        const resp = listCachedContentsResponseFromMldev(
          this.apiClient,
          apiResponse,
        );
        Object.setPrototypeOf(resp, types.ListCachedContentsResponse.prototype);
        return resp as types.ListCachedContentsResponse;
      });
    }
  }

  list = async (
    config?: types.ListCachedContentsConfig,
  ): Promise<Pager<types.CachedContent>> => {
    return new Pager<types.CachedContent>(
      PagedItem.PAGED_ITEM_CACHED_CONTENTS,
      this._list,
      await this._list(config),
      config,
    );
  };
}
